export default {
  users: [
    {
      username: "user01",
      email: "user01@gmail.com",
      password: "1234",
      communityID: "5fe76baab69d0843c44af87e",
      admin: false,
      registerTime: null,
      phoneNumber: "3658884030",
      addressID: "5fe76b8d1ccb4a626c67c33c",
      firstName: "",
      birthday: "",
      userImage: "",
      validateStatus: false,
      validateTime: null,
      balance: 0,
      superAdmin: false,
      lastName: "",
      country: "",
      address: "",

    },
    {
      username: "user02",
      email: "user02@gmail.com",
      password: "1234",
      communityID: "5fe76baab69d0843c44af87e",
      admin: false,
      registerTime: null,
      phoneNumber: "3658884030",
      addressID: "5fe76b8d1ccb4a626c67c33c",
      firstName: "",
      birthday: "",
      userImage: "",
      validateStatus: false,
      validateTime: null,
      balance: 0,
      superAdmin: false,
      lastName: "",
      country: "",
      address: "",
    },
    {
      username: "admin01",
      email: "admin01@gmail.com",
      password: "1234",
      communityID: "5fe76baab69d0843c44af87e",
      admin: true,
      registerTime: null,
      phoneNumber: "3658884030",
      addressID: "5fe76b8d1ccb4a626c67c33c",
      firstName: "",
      birthday: "",
      userImage: "",
      validateStatus: false,
      validateTime: null,
      balance: 0,
      superAdmin: false,
      lastName: "",
      country: "",
      address: "",
    },
    {
      username: "superAdmin01",
      email: "superAdmin01@gmail.com",
      password: "1234",
      communityID: "5fe76baab69d0843c44af87e",
      admin: false,
      registerTime: null,
      phoneNumber: "3658884030",
      addressID: "5fe76b8d1ccb4a626c67c33c",
      firstName: "",
      birthday: "",
      userImage: "",
      validateStatus: false,
      validateTime: null,
      balance: 0,
      superAdmin: true,
      lastName: "",
      country: "",
      address: "",
    },
  ],
}