//constants for creating a feedback record
export const FEEDBACK_CREATE_REQUEST = "FEEDBACK_CREATE_REQUEST";
export const FEEDBACK_CREATE_SUCCESS = "FEEDBACK_CREATE_SUCCESS";
export const FEEDBACK_CREATE_FAIL = "FEEDBACK_CREATE_FAIL";

//constants for getting a feedback
export const FEEDBACK_GET_REQUEST = "FEEDBACK_GET_REQUEST";
export const FEEDBACK_GET_SUCCESS = "FEEDBACK_GET_SUCCESS";
export const FEEDBACK_GET_FAIL = "FEEDBACK_GET_FAIL";

//constants for getting feedbacks of user (buyers)
export const GET_USER_FEEDBACKS_REQUEST = "GET_USER_FEEDBACKS_REQUEST";
export const GET_USER_FEEDBACKS_SUCCESS = "GET_USER_FEEDBACKS_SUCCESS";
export const GET_USER_FEEDBACKS_FAIL = "GET_USER_FEEDBACKS_FAIL";

//constants for getting feedbacks of rater
export const GET_RATER_FEEDBACKS_REQUEST = "GET_RATER_FEEDBACKS_REQUEST";
export const GET_RATER_FEEDBACKS_SUCCESS = "GET_RATER_FEEDBACKS_SUCCESS";
export const GET_RATER_FEEDBACKS_FAIL = "GET_RATER_FEEDBACKS_FAIL";
