//constants for creating a new item
export const ITEM_CREATE_REQUEST = 'ITEM_CREATE_REQUEST';
export const ITEM_CREATE_SUCCESS = 'ITEM_CREATE_SUCCESS';
export const ITEM_CREATE_FAIL = 'ITEM_CREATE_FAIL';

//constants for updating the information of an item
export const ITEM_UPDATE_REQUEST = 'ITEM_UPDATE_REQUEST';
export const ITEM_UPDATE_SUCCESS = 'ITEM_UPDATE_SUCCESS';
export const ITEM_UPDATE_FAIL = 'ITEM_UPDATE_FAIL';

//constants for updating the image of an item
export const ITEM_UPDATE_IMAGE_REQUEST = 'ITEM_UPDATE_IMAGE_REQUEST';
export const ITEM_UPDATE_IMAGE_SUCCESS = 'ITEM_UPDATE_IMAGE_SUCCESS';
export const ITEM_UPDATE_IMAGE_FAIL = 'ITEM_UPDATE_IMAGE_FAIL';

//constants for delete an item
export const ITEM_DELETE_REQUEST = 'ITEM_DELETE_REQUEST';
export const ITEM_DELETE_SUCCESS = 'ITEM_DELETE_SUCCESS';
export const ITEM_DELETE_FAIL = 'ITEM_DELETE_FAIL';

//constants for getting a item detail information
export const ITEM_GET_REQUEST = 'ITEM_GET_REQUEST';
export const ITEM_GET_SUCCESS = 'ITEM_GET_SUCCESS';
export const ITEM_GET_FAIL = 'ITEM_GET_FAIL';

//constants for getting a list of the newest items from different categories
export const NEWEST_ITEM_LIST_PRODUCTS_REQUEST = 'NEWEST_ITEM_LIST_PRODUCTS_REQUEST';
export const NEWEST_ITEM_LIST_PRODUCTS_SUCCESS = 'NEWEST_ITEM_LIST_PRODUCTS_SUCCESS';
export const NEWEST_ITEM_LIST_PRODUCTS_FAIL = 'NEWEST_ITEM_LIST_PRODUCTS_FAIL';
export const NEWEST_ITEM_LIST_SERVICES_REQUEST = 'NEWEST_ITEM_LIST_SERVICES_REQUEST';
export const NEWEST_ITEM_LIST_SERVICES_SUCCESS = 'NEWEST_ITEM_LIST_SERVICES_SUCCESS';
export const NEWEST_ITEM_LIST_SERVICES_FAIL = 'NEWEST_ITEM_LIST_SERVICES_FAIL';
export const NEWEST_ITEM_LIST_EXPERTISES_REQUEST = 'NEWEST_ITEM_LIST_EXPERTISES_REQUEST';
export const NEWEST_ITEM_LIST_EXPERTISES_SUCCESS = 'NEWEST_ITEM_LIST_EXPERTISES_SUCCESS';
export const NEWEST_ITEM_LIST_EXPERTISES_FAIL = 'NEWEST_ITEM_LIST_EXPERTISES_FAIL';

//constants for getting a list of items in a category
export const ITEM_LIST_CATEGORY_REQUEST = 'ITEM_LIST_CATEGORY_REQUEST';
export const ITEM_LIST_CATEGORY_SUCCESS = 'ITEM_LIST_CATEGORY_SUCCESS';
export const ITEM_LIST_CATEGORY_FAIL = 'ITEM_LIST_CATEGORY_FAIL';

//constants for getting a list of items for a user
export const ITEM_LIST_USER_REQUEST = 'ITEM_LIST_USER_REQUEST';
export const ITEM_LIST_USER_SUCCESS = 'ITEM_LIST_USER_SUCCESS';
export const ITEM_LIST_USER_FAIL = 'ITEM_LIST_USER_FAIL';

//constants for getting a list of items in a subcategory
export const ITEM_LIST_SUBCATEGORY_REQUEST = 'ITEM_LIST_SUBCATEGORY_REQUEST';
export const ITEM_LIST_SUBCATEGORY_SUCCESS = 'ITEM_LIST_SUBCATEGORY_SUCCESS';
export const ITEM_LIST_SUBCATEGORY_FAIL = 'ITEM_LIST_SUBCATEGORY_FAIL';


