export const ITEM_CREATE_REQUEST = 'ITEM_CREATE_REQUEST';
export const ITEM_CREATE_SUCCESS = 'ITEM_CREATE_SUCCESS';
export const ITEM_CREATE_FAIL = 'ITEM_CREATE_FAIL';

export const ITEM_UPDATE_REQUEST = 'ITEM_UPDATE_REQUEST';
export const ITEM_UPDATE_SUCCESS = 'ITEM_UPDATE_SUCCESS';
export const ITEM_UPDATE_FAIL = 'ITEM_UPDATE_FAIL';

export const ITEM_UPDATE_IMAGE_REQUEST = 'ITEM_UPDATE_IMAGE_REQUEST';
export const ITEM_UPDATE_IMAGE_SUCCESS = 'ITEM_UPDATE_IMAGE_SUCCESS';
export const ITEM_UPDATE_IMAGE_FAIL = 'ITEM_UPDATE_IMAGE_FAIL';

export const ITEM_DELETE_REQUEST = 'ITEM_DELETE_REQUEST';
export const ITEM_DELETE_SUCCESS = 'ITEM_DELETE_SUCCESS';
export const ITEM_DELETE_FAIL = 'ITEM_DELETE_FAIL';

export const ITEM_GET_REQUEST = 'ITEM_GET_REQUEST';
export const ITEM_GET_SUCCESS = 'ITEM_GET_SUCCESS';
export const ITEM_GET_FAIL = 'ITEM_GET_FAIL';

export const ITEM_LIST_REQUEST = 'ITEM_LIST_REQUEST';
export const ITEM_LIST_SUCCESS = 'ITEM_LIST_SUCCESS';
export const ITEM_LIST_FAIL = 'ITEM_LIST_FAIL';

export const ITEM_LIST_CATEGORY_REQUEST = 'ITEM_LIST_CATEGORY_REQUEST';
export const ITEM_LIST_CATEGORY_SUCCESS = 'ITEM_LIST_CATEGORY_SUCCESS';
export const ITEM_LIST_CATEGORY_FAIL = 'ITEM_LIST_CATEGORY_FAIL';

export const ITEM_LIST_USER_REQUEST = 'ITEM_LIST_USER_REQUEST';
export const ITEM_LIST_USER_SUCCESS = 'ITEM_LIST_USER_SUCCESS';
export const ITEM_LIST_USER_FAIL = 'ITEM_LIST_USER_FAIL';

export const ITEM_LIST_SUBCATEGORY_REQUEST = 'ITEM_LIST_SUBCATEGORY_REQUEST';
export const ITEM_LIST_SUBCATEGORY_SUCCESS = 'ITEM_LIST_SUBCATEGORY_SUCCESS';
export const ITEM_LIST_SUBCATEGORY_FAIL = 'ITEM_LIST_SUBCATEGORY_FAIL';


