//constants for get a transaction details
export const TRANSACTION_GET_REQUEST = 'TRANSACTION_GET_REQUEST';
export const TRANSACTION_GET_SUCCESS = 'TRANSACTION_GET_SUCCESS';
export const TRANSACTION_GET_FAIL = 'TRANSACTION_GET_FAIL';

//constants for get a list of transactions for a user
export const TRANSACTION_OF_USER_GET_REQUEST = 'TRANSACTION_OF_USER_GET_REQUEST';
export const TRANSACTION_OF_USER_GET_SUCCESS = 'TRANSACTION_OF_USER_GET_SUCCESS';
export const TRANSACTION_OF_USER_GET_FAIL = 'TRANSACTION_OF_USER_GET_FAIL';

//constants for get a balance for a user
export const BALANCE_GET_REQUEST = 'BALANCE_GET_REQUEST';
export const BALANCE_GET_SUCCESS = 'BALANCE_GET_SUCCESS';
export const BALANCE_GET_FAIL = 'BALANCE_GET_FAIL';

//constants for add balance to a user
export const BALANCE_ADD_REQUEST = 'BALANCE_ADD_REQUEST';
export const BALANCE_ADD_SUCCESS = 'BALANCE_ADD_SUCCESS';
export const BALANCE_ADD_FAIL = 'BALANCE_ADD_FAIL';

//constants for deduct balance to a user
export const BALANCE_DEDUCT_REQUEST = 'BALANCE_DEDUCT_REQUEST';
export const BALANCE_DEDUCT_SUCCESS = 'BALANCE_DEDUCT_SUCCESS';
export const BALANCE_DEDUCT_FAIL = 'BALANCE_DEDUCT_FAIL';

//constants for creating a transaction
export const TRANSACTION_CREATE_REQUEST = "TRANSACTION_CREATE_REQUEST";
export const TRANSACTION_CREATE_SUCCESS = "TRANSACTION_CREATE_SUCCESS";
export const TRANSACTION_CREATE_FAIL = "TRANSACTION_CREATE_FAIL";
